server:
  port: 8070

spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: wiki
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/wiki/**
        - id: wiki-swagger
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/wiki/v3/api-docs/**, /wiki/swagger-ui/**




springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: wiki
        url: /wiki/v3/api-docs

    displayOperationId: true
    tryItOutEnabled: true
